package com.casaraodocampo.movprod;
import android.app.*;import android.os.*;import android.content.*;import android.database.*;import android.database.sqlite.*;import android.graphics.*;import android.graphics.pdf.PdfDocument;import android.net.Uri;import android.view.*;import android.widget.*;import android.text.*;import java.io.*;import java.text.*;import java.util.*;import javax.xml.parsers.*;import org.w3c.dom.*;
public class MainActivity extends Activity{
 DB db;LinearLayout body;int G=Color.rgb(29,70,56),PICK=7;int dp(int n){return(int)(n*getResources().getDisplayMetrics().density);}Button bt(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setBackgroundColor(G);return b;}TextView tv(String s,int z){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(G);t.setPadding(dp(8),dp(8),dp(8),dp(8));return t;}
 public void onCreate(Bundle b){super.onCreate(b);db=new DB(this);home();}
 void shell(String title){ScrollView sv=new ScrollView(this);LinearLayout a=new LinearLayout(this);a.setOrientation(LinearLayout.VERTICAL);a.setPadding(dp(10),dp(10),dp(10),dp(20));sv.addView(a);ImageView im=new ImageView(this);im.setImageResource(R.drawable.rotulo);im.setScaleType(ImageView.ScaleType.FIT_CENTER);im.setAdjustViewBounds(true);a.addView(im,new LinearLayout.LayoutParams(-1,dp(330)));TextView h=tv("MOVIMENTAÇÃO DE PRODUTOS\n"+title,21);h.setGravity(17);a.addView(h);LinearLayout n=new LinearLayout(this);String[]ns={"ESTOQUE","IMPORTAR XML","SAÍDA / VENDA","HISTÓRICO","PDFs"};for(int i=0;i<5;i++){Button x=bt(ns[i]);final int k=i;x.setOnClickListener(v->{if(k==0)home();if(k==1)pick();if(k==2)saida();if(k==3)historico();if(k==4)pdfs();});n.addView(x,new LinearLayout.LayoutParams(0,dp(55),1));}a.addView(n);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);a.addView(body);setContentView(sv);}
 void home(){shell("ESTOQUE");EditText q=new EditText(this);q.setHint("🔍 Pesquisar código ou produto");q.setSingleLine();body.addView(q);LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);body.addView(l);Runnable load=()->{l.removeAllViews();String z=q.getText().toString().toLowerCase();for(String[]p:db.products()){if(z.isEmpty()||(p[0]+" "+p[1]).toLowerCase().contains(z)){Button b=bt("✎  "+p[0]+" - "+p[1]+"\nAnterior: "+p[3]+" | Entrou: "+p[4]+" | Saiu: "+p[5]+" | Atual: "+p[6]+" "+p[2]);b.setAllCaps(false);l.addView(b,new LinearLayout.LayoutParams(-1,dp(78)));String c=p[0];b.setOnClickListener(v->editarProduto(c));}}};q.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){load.run();}public void afterTextChanged(Editable e){}});load.run();}
 void editarProduto(String c){String[]p=db.product(c);LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);EditText n=new EditText(this);n.setHint("Descrição");n.setText(p[1]);x.addView(n);EditText u=new EditText(this);u.setHint("Unidade");u.setText(p[2]);x.addView(u);new AlertDialog.Builder(this).setTitle("✎ EDITAR PRODUTO "+c).setView(x).setPositiveButton("SALVAR",(d,w)->{db.editProduct(c,n.getText().toString(),u.getText().toString());home();}).setNeutralButton("HISTÓRICO DO PRODUTO",(d,w)->produto(c)).setNegativeButton("CANCELAR",null).show();}
 void produto(String c){shell("PRODUTO");String[]p=db.product(c);body.addView(tv(String.join(" | ",p),17));for(String x:db.hist(c))body.addView(tv(x,13));Button b=bt("GERAR PDF DESTE PRODUTO");body.addView(b);b.setOnClickListener(v->pdf("PRODUTO_"+c,db.repProd(c)));}
 void pick(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,PICK);}
 protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r!=PICK||c!=RESULT_OK||d==null)return;try{int arq=0,nov=0,it=0;if(d.getClipData()!=null){for(int i=0;i<d.getClipData().getItemCount();i++){int[]x=xml(d.getClipData().getItemAt(i).getUri());arq++;nov+=x[0];it+=x[1];}}else{int[]x=xml(d.getData());arq++;nov+=x[0];it+=x[1];}new AlertDialog.Builder(this).setTitle("XML IMPORTADO").setMessage("Arquivos: "+arq+"\nItens: "+it+"\nProdutos novos: "+nov).setPositiveButton("OK",(x,w)->home()).show();}catch(Exception e){new AlertDialog.Builder(this).setTitle("ERRO XML").setMessage(e.toString()).setPositiveButton("OK",null).show();}}
 int[] xml(Uri u)throws Exception{InputStream in=getContentResolver().openInputStream(u);Document d=DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(in);in.close();String nf=text(d,"nNF"),ch="";NodeList inf=d.getElementsByTagName("infNFe");if(inf.getLength()>0)ch=((Element)inf.item(0)).getAttribute("Id").replace("NFe","");int nv=0,it=0;NodeList ds=d.getElementsByTagName("det");for(int i=0;i<ds.getLength();i++){Element det=(Element)ds.item(i),pr=(Element)det.getElementsByTagName("prod").item(0);if(pr==null)continue;String cp=text(pr,"cProd"),xp=text(pr,"xProd"),un=text(pr,"uCom"),qq=text(pr,"qCom");if(cp.isEmpty())continue;if(!db.exists(cp)){db.addProduct(cp,xp,un);nv++;}db.move(cp,"ENTRADA",num(qq),"XML NF "+nf+" CHAVE "+ch);it++;}return new int[]{nv,it};}
 String text(Document d,String t){NodeList n=d.getElementsByTagName(t);return n.getLength()>0?n.item(0).getTextContent().trim():"";}String text(Element e,String t){NodeList n=e.getElementsByTagName(t);return n.getLength()>0?n.item(0).getTextContent().trim():"";}double num(String s){try{return Double.parseDouble(s.replace(",","."));}catch(Exception e){return 0;}}
 void saida(){shell("SAÍDA / VENDA");ArrayList<String[]>ps=db.products();ArrayList<String>la=new ArrayList<>();for(String[]p:ps)la.add(p[0]+" - "+p[1]);Spinner sp=new Spinner(this);sp.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,la));body.addView(sp);EditText q=new EditText(this);q.setHint("Quantidade");body.addView(q);EditText cli=new EditText(this);cli.setHint("Cliente / Destinatário");body.addView(cli);EditText dest=new EditText(this);dest.setHint("Destino / Local");body.addView(dest);EditText o=new EditText(this);o.setHint("Observação / Pedido");body.addView(o);Button b=bt("SALVAR SAÍDA / VENDA E GERAR PDF");body.addView(b);b.setOnClickListener(v->{double n=num(q.getText().toString());if(n>0&&ps.size()>0){String obs="Cliente: "+cli.getText()+" | Destino: "+dest.getText()+" | "+o.getText();long id=db.moveId(ps.get(sp.getSelectedItemPosition())[0],"SAIDA",n,obs);pdf("SAIDA_PEDIDO_"+id,db.repMove(id));}});}
 void historico(){shell("HISTÓRICO DE SAÍDAS / VENDAS");for(String[]m:db.saidas()){Button b=bt(m[0]+" | "+m[1]+"\n"+m[2]+" | Qtd: "+m[3]+"\n"+m[4]);b.setAllCaps(false);body.addView(b,new LinearLayout.LayoutParams(-1,dp(95)));long id=Long.parseLong(m[0]);b.setOnClickListener(v->pdf("SAIDA_PEDIDO_"+id,db.repMove(id)));}}
 void pdfs(){shell("PDFs");Button a=bt("PDF DA BASE INTEIRA");body.addView(a);a.setOnClickListener(v->pdf("ESTOQUE_GERAL",db.repAll()));Button m=bt("PDF DE TODAS AS MOVIMENTAÇÕES");body.addView(m);m.setOnClickListener(v->pdf("MOVIMENTACOES",db.repMov()));}
 void pdf(String title,ArrayList<String>ls){try{PdfDocument d=new PdfDocument();Paint p=new Paint();p.setColor(Color.BLACK);p.setTextSize(9);int pg=1,y=50;PdfDocument.Page page=d.startPage(new PdfDocument.PageInfo.Builder(595,842,pg).create());Canvas c=page.getCanvas();c.drawText("CASARÃO DO CAMPO - "+title,30,30,p);for(String s:ls){for(int a=0;a<s.length();a+=100){if(y>810){d.finishPage(page);page=d.startPage(new PdfDocument.PageInfo.Builder(595,842,++pg).create());c=page.getCanvas();y=40;}c.drawText(s.substring(a,Math.min(a+100,s.length())),30,y,p);y+=13;}y+=2;}d.finishPage(page);File dir=new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS),"Movimentação de Produtos Casarão do Campo");dir.mkdirs();File f=new File(dir,title+"_"+new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date())+".pdf");FileOutputStream o=new FileOutputStream(f);d.writeTo(o);o.close();d.close();new AlertDialog.Builder(this).setTitle("PDF GERADO").setMessage(f.getAbsolutePath()).setPositiveButton("OK",null).show();}catch(Exception e){new AlertDialog.Builder(this).setTitle("ERRO PDF").setMessage(e.toString()).show();}}
}
class DB extends SQLiteOpenHelper{Context ctx;DB(Context c){super(c,"movprod.db",null,1);ctx=c;}public void onCreate(SQLiteDatabase d){d.execSQL("create table produtos(codigo text primary key,descricao text,unidade text,saldo_inicial real default 0)");d.execSQL("create table mov(id integer primary key autoincrement,codigo text,data text,tipo text,qtd real,obs text)");seed(d);}public void onUpgrade(SQLiteDatabase d,int a,int b){}
 void seed(SQLiteDatabase d){try{BufferedReader br=new BufferedReader(new InputStreamReader(ctx.getAssets().open("produtos_base.csv"),"UTF-8"));String l;br.readLine();while((l=br.readLine())!=null){ArrayList<String>x=csv(l);if(x.size()>2)d.execSQL("insert or ignore into produtos values(?,?,?,0)",new Object[]{x.get(0),x.get(1),x.get(2)});}br.close();}catch(Exception e){}}
 ArrayList<String>csv(String l){ArrayList<String>a=new ArrayList<>();StringBuilder s=new StringBuilder();boolean q=false;for(int i=0;i<l.length();i++){char c=l.charAt(i);if(c=='\"')q=!q;else if(c==','&&!q){a.add(s.toString());s.setLength(0);}else s.append(c);}a.add(s.toString());return a;}
 boolean exists(String c){Cursor x=getReadableDatabase().rawQuery("select 1 from produtos where codigo=?",new String[]{c});return x.moveToFirst();}
 void editProduct(String c,String n,String u){getWritableDatabase().execSQL("update produtos set descricao=?,unidade=? where codigo=?",new Object[]{n,u,c});}
 long moveId(String c,String t,double q,String o){ContentValues v=new ContentValues();v.put("codigo",c);v.put("data",new SimpleDateFormat("dd/MM/yyyy HH:mm").format(new Date()));v.put("tipo",t);v.put("qtd",q);v.put("obs",o);return getWritableDatabase().insert("mov",null,v);}
 ArrayList<String[]> saidas(){ArrayList<String[]>a=new ArrayList<>();Cursor x=getReadableDatabase().rawQuery("select m.id,m.data,m.codigo,p.descricao,m.qtd,m.obs from mov m join produtos p on p.codigo=m.codigo where m.tipo='SAIDA' order by m.id desc",null);while(x.moveToNext())a.add(new String[]{x.getString(0),x.getString(1),x.getString(2)+" - "+x.getString(3),f(x.getDouble(4)),x.getString(5)});return a;}
 ArrayList<String> repMove(long id){ArrayList<String>a=new ArrayList<>();Cursor x=getReadableDatabase().rawQuery("select m.id,m.data,m.codigo,p.descricao,p.unidade,m.qtd,m.obs from mov m join produtos p on p.codigo=m.codigo where m.id=?",new String[]{String.valueOf(id)});if(x.moveToFirst()){a.add("SAÍDA / PEDIDO Nº "+x.getString(0));a.add("Data: "+x.getString(1));a.add("Produto: "+x.getString(2)+" - "+x.getString(3));a.add("Quantidade: "+f(x.getDouble(5))+" "+x.getString(4));a.add(x.getString(6));}return a;}void addProduct(String c,String n,String u){getWritableDatabase().execSQL("insert or ignore into produtos values(?,?,?,0)",new Object[]{c,n,u});}void move(String c,String t,double q,String o){getWritableDatabase().execSQL("insert into mov(codigo,data,tipo,qtd,obs) values(?,?,?,?,?)",new Object[]{c,new SimpleDateFormat("dd/MM/yyyy HH:mm").format(new Date()),t,q,o});}
 double sum(String c,String t){Cursor x=getReadableDatabase().rawQuery("select coalesce(sum(qtd),0) from mov where codigo=? and tipo=?",new String[]{c,t});x.moveToFirst();return x.getDouble(0);}String f(double v){return String.format(Locale.US,"%.3f",v).replace(".",",");}String[] calc(String c,String n,String u){double en=sum(c,"ENTRADA"),sa=sum(c,"SAIDA"),at=en-sa,ant=at;Cursor x=getReadableDatabase().rawQuery("select tipo,qtd from mov where codigo=? order by id desc limit 1",new String[]{c});if(x.moveToFirst())ant=at+(x.getString(0).equals("SAIDA")?x.getDouble(1):-x.getDouble(1));return new String[]{c,n,u,f(ant),f(en),f(sa),f(at)};}
 ArrayList<String[]>products(){ArrayList<String[]>a=new ArrayList<>();Cursor x=getReadableDatabase().rawQuery("select codigo,descricao,unidade from produtos order by cast(codigo as integer),codigo",null);while(x.moveToNext())a.add(calc(x.getString(0),x.getString(1),x.getString(2)));return a;}String[]product(String c){Cursor x=getReadableDatabase().rawQuery("select codigo,descricao,unidade from produtos where codigo=?",new String[]{c});x.moveToFirst();return calc(x.getString(0),x.getString(1),x.getString(2));}
 ArrayList<String>hist(String c){ArrayList<String>a=new ArrayList<>();Cursor x=getReadableDatabase().rawQuery("select data,tipo,qtd,obs from mov where codigo=? order by id desc",new String[]{c});while(x.moveToNext())a.add(x.getString(0)+" | "+x.getString(1)+" | "+f(x.getDouble(2))+" | "+x.getString(3));return a;}ArrayList<String>repProd(String c){ArrayList<String>a=new ArrayList<>();a.add("Código | Produto | U.M. | Saldo anterior | Entrada | Saída | Saldo atual");a.add(String.join(" | ",product(c)));a.addAll(hist(c));return a;}ArrayList<String>repAll(){ArrayList<String>a=new ArrayList<>();a.add("Código | Produto | U.M. | Saldo anterior | Entrada | Saída | Saldo atual");for(String[]p:products())a.add(String.join(" | ",p));return a;}ArrayList<String>repMov(){ArrayList<String>a=new ArrayList<>();Cursor x=getReadableDatabase().rawQuery("select m.data,m.codigo,p.descricao,m.tipo,m.qtd,m.obs from mov m join produtos p on p.codigo=m.codigo order by m.id desc",null);while(x.moveToNext())a.add(x.getString(0)+" | "+x.getString(1)+" | "+x.getString(2)+" | "+x.getString(3)+" | "+f(x.getDouble(4))+" | "+x.getString(5));return a;}}
